matrix:
        include:
              - language: cpp
                        script: make all
              - language: python
                python: "3.6"
                install:
                  - pip install -r ./Py/requirements.txt
