language: cpp
os: linux
dist: bionic
compiler: g++
before_install: 
        - pyenv global 3.8
script: 
        - cd Dependencies
        - cd pybind11
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cd .. && cd .. && cd ..
        - make all

