language: cpp
os: linux
dist: bionic
compiler: g++
before_install: 
        - pyenv global 3.8
        - pip install pybind11
        - pip install pytest
script: 
        - cd Dependencies
        - cd pybind11
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cd .. && cd .. && cd ..
        - python3 --version
        - make all
        - cd Tests
        - python3 test_main.py

